if [[ -d $HOME/.composer/vendor/bin ]]; then
  export PATH=$PATH:$HOME/.composer/vendor/bin
fi

export TERM=xterm-256color

alias mc='. /usr/share/mc/bin/mc-wrapper.sh'

function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ \1 /'
}

export PS1="\[\e[42;30m\] \u@\h \[\e[0m\]\[\e[43;30m\] \w \[\e[0m\]\[\e[46;30m\]\$(parse_git_branch)\[\e[0m\]\n\[\e[01;30m\]$ \[\e[0m\]"

HISTSIZE=15000
HISTFILESIZE=15000
HISTTIMEFORMAT='%d.%m.%y %T '

